Version: '8.4'
VersionCheck: true
VersionCheckCycle: 10800
VersionDownload: true
DropForm: normal
PickForm: normal
PitchX: 100
PitchY: 135
PitchZ: 100
EnableCoverBlock: false
EnableAliases: true
ShowItemInfo: true
DropItemAI: true
Language: en_US
NaturalSpawn: true
AllowedPlayer: true
AllowedPlayers: MidCoard
BanItem: AIR
RefreshTime: 300
Height: 0.3
Angles:
  - AIR 100 135 100